/**
 * Iconografia IAgro — família única (Lucide via react-icons/lu).
 * Importe ícones daqui para manter consistência de traço e permitir troca central.
 */
export {
  // base / auth
  LuEye,
  LuEyeOff,
  LuArrowLeft,
  LuArrowRight,
  LuCheck,
  LuShieldCheck,
  LuCircleCheck,
  LuCircle,
  LuLoaderCircle,
  LuTriangleAlert,
  LuInfo,
  LuX,
  // termos
  LuFileText,
  LuLaptop,
  LuLock,
  LuUser,
  LuMail,
  LuLeaf,
  LuChevronRight,
  // app shell
  LuHouse,
  LuChartColumn,
  LuHistory,
  LuBell,
  LuSearch,
  LuLogOut,
  LuChevronDown,
  LuSparkles,
  LuPlus,
  LuWarehouse,
  LuMenu,
  // dashboard
  LuSun,
  LuWind,
  LuDroplet,
  LuTrendingUp,
  LuTrendingDown,
  LuDollarSign,
  LuClipboardList,
  LuFlaskConical,
  LuCalendar,
  // análises / calculadoras
  LuDownload,
  LuChartPie,
  LuGauge,
  LuCalculator,
  LuChartColumnBig,
  // histórico / tarefas / perfil / assistente
  LuFilter,
  LuTrash2,
  LuPencil,
  LuEllipsisVertical,
  LuChevronLeft,
  LuArrowUpDown,
  LuClock,
  LuCircleAlert,
  LuSend,
  LuSettings,
  LuBell as LuBellOutline,
  LuMapPin,
  LuPhone,
  LuBriefcase,
  LuPalette,
  LuShield,
  LuPlug,
} from 'react-icons/lu';
